# Generated by Django 4.2.4 on 2023-08-17 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=150, verbose_name='Название курса')),
                ('description', models.TextField(max_length=500, verbose_name='Описание курса')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='превью')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=150, verbose_name='Название урока')),
                ('description', models.TextField(max_length=500, verbose_name='Описание урока')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='превью')),
                ('linkvideo', models.URLField(blank=True, null=True, verbose_name='превью')),
            ],
            options={
                'verbose_name': 'Урок ',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150, verbose_name='Пользователь')),
                ('date_of_payment', models.CharField(max_length=30, verbose_name='Дата Платежа')),
                ('amount_of_payment', models.IntegerField(verbose_name='Сумма оплаты')),
                ('way_of_payment', models.CharField(max_length=150, verbose_name='Способ оплаты')),
                ('paid_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.course', verbose_name='Оплаченый курс')),
                ('paid_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson', verbose_name='Оплаченный урок')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
